#!/bin/bash

docker-compose exec --user=www-data -e https_proxy=$http_proxy -e http_proxy=$http_proxy php bash -c "cd server && composer install"

docker-compose exec --user=www-data -e http_proxy=$http_proxy -e http_proxy=$http_proxy php bash -c \
    "sudo chown -R www-data:www-data /home/www-data \
    && cd client \
    && npm config set proxy $http_proxy \
    && yarn install"

docker-compose exec --user=www-data -e https_proxy=$http_proxy -e http_proxy=$http_proxy php bash -c \
    "cd server && ./bin/console doctrine:schema:create"