version: '3'
services:
  db:
    image: mysql:5.6
    volumes:
    - ./docker/db/data:/var/lib/mysql
    ports:
    - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    build:
      context: docker/php
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    links:
      - db
    ports:
      - ${PHP_PORT}:9000
    working_dir: /var/www/html/application/server
    volumes:
      - ./application:/var/www/html/application:cached
      - ./docker/php/logs:/var/log
  web:
    image: nginx:1.11
    ports:
      - ${APP_WEB_PORT}:80
    depends_on:
      - php
    volumes:
      - ./application:/var/www/html/application:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/data:/var/log/nginx