Post:
    type: object
    config:
        description: "An article posted in the blog."
        fields:
            id:
                type: "ID!"
            title:
                type: "String"
                description: "The article's title"
            text:
                type: "String"
                description: "The article's content"
            createdAt:
                type: "DateTime"
            updatedAt:
                type: "DateTime"
            comments:
                type: "[Comment]"